/** Offline UI regression: PORTAL_URL=http://localhost:4399 node qa/portal/messages-ui.mjs.
 * MESSAGES_UI_CAPTURE_ONLY=1 skips behavioral assertions and writes the viewport screenshots. */
import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { createMessagesFixture } from './messages-ui-fixture.mjs';
const out='test-results/messages-ui';mkdirSync(out,{recursive:true});const browser=await chromium.launch(),failures=[];
const check=async(name,work)=>{try{await work();console.log(`PASS: ${name}`);}catch(e){failures.push(`${name}: ${e.message}`);console.error(`FAIL: ${name}: ${e.message}`);}};
try {
 const {page,context,state,base}=await createMessagesFixture(browser);
 const fresh=async()=>{await page.goto(`${base}/alumni-portal/admin/messages`);await expect(page.locator('[data-template="0"]')).toBeVisible({timeout:15000});await expect(page.locator('[data-action="send"]')).toBeEnabled();};
 const group=()=>page.locator('[data-group="TECH"][data-who="alumni"]');
 for(const width of [320,390,768,1024,1440]) await check(`layout and interactions ${width}px`,async()=>{
  await page.setViewportSize({width,height:900});await fresh();await page.locator('[data-template="0"]').click();await group().click();await page.locator('[data-when] [data-value="later"]').click();
  await expect(page.locator('[data-sms-bubble]')).toContainText('TroyLabs:');await expect(page.locator('[data-who-list]')).toBeVisible();
  const overflow=await page.evaluate(()=>[...document.querySelectorAll('.portal-col *')].filter(el=>{const r=el.getBoundingClientRect();return r.width&&r.height&&(r.right>innerWidth+1||r.left < -1);}).map(el=>({class:el.className,text:el.textContent.slice(0,60)})));
  assert.deepEqual(overflow,[]);await page.locator('[data-action="preview"]').click();await expect(page.locator('[data-who-list]')).toHaveAttribute('open','');await page.locator('.msg-automatic > summary').click();await expect(page.locator('[data-auto-texts]')).toBeVisible();await page.locator('.msg-automatic > summary').click();mkdirSync(out,{recursive:true});await page.screenshot({path:`${out}/messages-${width}.png`,fullPage:true});
 });
 if(!process.env.MESSAGES_UI_CAPTURE_ONLY){
  await check('scheduled edit preserves local time',async()=>{await fresh();await page.locator('[data-edit="900002"]').click();await expect(page.locator('#mc-when')).toHaveValue('2030-10-08T10:00');});
  await check('draft edit clears previous schedule',async()=>{await fresh();await page.locator('[data-edit="900002"]').click();await page.locator('[data-edit="900001"]').click();await expect(page.locator('[data-when] [data-value="now"]')).toHaveAttribute('aria-pressed','true');await expect(page.locator('#mc-when')).toHaveValue('');});
  await check('New Draft clears previous schedule',async()=>{await fresh();await page.locator('[data-edit="900002"]').click();await page.locator('[data-action="new-draft"]').click();await expect(page.locator('[data-when] [data-value="now"]')).toHaveAttribute('aria-pressed','true');await expect(page.locator('#mc-when')).toHaveValue('');});
  await check('template clears previous schedule',async()=>{await fresh();await page.locator('[data-edit="900002"]').click();await page.locator('[data-template="0"]').click();await expect(page.locator('[data-when] [data-value="now"]')).toHaveAttribute('aria-pressed','true');await expect(page.locator('#mc-when')).toHaveValue('');});
  const scheduled=async()=>{await fresh();await page.locator('#mc-title').fill('Test announcement');await page.locator('#mc-body').fill('A short test body.');await group().click();await page.locator('[data-when] [data-value="later"]').click();await page.locator('#mc-when').fill('2030-10-08T10:00');};
  await check('schedule rejects missing subject',async()=>{await scheduled();await page.locator('#mc-title').fill('');const n=state.writes.length;await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText(/subject/i);assert.equal(state.writes.length,n);});
  await check('schedule rejects zero recipients',async()=>{await scheduled();await group().click();await page.locator('[data-group="DEMO"][data-who="alumni"]').click();const n=state.writes.length;await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText(/nobody|no (eligible|reachable|matching)|0 (people|recipients)/i);assert.equal(state.writes.length,n);});
  await check('schedule rejects oversized SMS',async()=>{await scheduled();await page.locator('[data-single]:not([data-when]) [data-value="text"]').click();await page.locator('#mc-body').fill('a'.repeat(2000));const n=state.writes.length;await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText(/too long|shorten/i);assert.equal(state.writes.length,n);});
  // texts have no subject: TEXT hides the box; a text-only message is named by the start of its body; email still needs one
  const textBtn=()=>page.locator('[data-single]:not([data-when]) [data-value="text"]'),subj=()=>page.locator('[data-subject-field]');
  await check('TEXT hides the subject, EMAIL and BOTH show it',async()=>{await fresh();await expect(subj()).toBeVisible();await textBtn().click();await expect(subj()).toBeHidden();await expect(page.locator('#mc-body')).toBeVisible();await page.locator('[data-single]:not([data-when]) [data-value="both"]').click();await expect(subj()).toBeVisible();await page.locator('[data-single]:not([data-when]) [data-value="email"]').click();await expect(subj()).toBeVisible();});
  await check('text-only schedule needs no subject; history name = start of the text',async()=>{await scheduled();await page.locator('#mc-title').fill('');await textBtn().click();const body='Demo night is this Thursday at 7 PM in the Iovine and Young Hall commons, bring a friend';await page.locator('#mc-body').fill(body);const n=state.writes.length;await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText('Scheduled');assert.equal(state.writes.length,n+1);const w=state.writes.at(-1).body;assert.equal(w.send_by,'text');assert.ok(w.title.endsWith('…')&&w.title.length<=61&&body.startsWith(w.title.slice(0,-1)),w.title);});
  await check('text-only with an empty body asks for the message, not a subject',async()=>{await scheduled();await textBtn().click();await page.locator('#mc-body').fill('');const n=state.writes.length;await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText('Write the message first');assert.equal(state.writes.length,n);});
  await check('short text: the whole body is the name',async()=>{await scheduled();await page.locator('#mc-title').fill('ignored subject');await textBtn().click();await page.locator('#mc-body').fill('See you at DEMO tonight!');await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText('Scheduled');assert.equal(state.writes.at(-1).body.title,'See you at DEMO tonight!');});
  await check('valid schedule uses UTC instant',async()=>{await scheduled();const n=state.writes.length;await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText('Scheduled');assert.equal(state.writes.length,n+1);assert.equal(state.writes.at(-1).body.scheduled_for,'2030-10-08T17:00:00.000Z');});
  await check('draft save remains allowed without audience',async()=>{await fresh();await page.locator('#mc-body').fill('Unfinished draft');const n=state.writes.length;await page.locator('[data-action="draft"]').click();await expect(page.locator('#msg-fb')).toContainText(/saved as a draft/i);assert.equal(state.writes.length,n+1);});
  await check('test of a scheduled message preserves original',async()=>{await fresh();await page.locator('[data-edit="900002"]').click();const original=structuredClone(state.messages.find(m=>m.id===900002));const n=state.writes.length;await page.locator('[data-action="test-send"]').click();await expect(page.locator('#msg-fb')).toContainText(/original schedule is unchanged/i);assert.equal(state.writes[n].method,'POST');assert.deepEqual(state.messages.find(m=>m.id===900002),original);assert.equal(state.calls.at(-1).mode==='welcome-backlog'||state.calls.some(c=>c.mode==='test'),true);});
  await check('recipient disclosure opens and history tabs filter',async()=>{await fresh();await page.locator('[data-msg-tabs] [data-value="sent"]').click();await expect(page.locator('[data-msg-list] > li[data-state]:visible')).toHaveCount(1);await page.locator('[data-recipients-for="900003"]').click();await expect(page.locator('[data-msg-list] > li[data-state="sent"] .portal-recipients')).toBeVisible();await expect(page.locator('[data-msg-list] > li[data-state="sent"] .portal-recipients')).toContainText('DELIVERED');});
  await check('zero-recipient send never invokes sending',async()=>{await fresh();await page.locator('#mc-title').fill('Empty group');await page.locator('#mc-body').fill('A short message');await page.locator('[data-group="DEMO"][data-who="alumni"]').click();const n=state.calls.filter(c=>c.mode==='send').length;await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText(/nobody/i);assert.equal(state.calls.filter(c=>c.mode==='send').length,n);});
  await check('schedule rejects past and outside texting hours',async()=>{await scheduled();await page.locator('#mc-when').fill('2020-01-01T10:00');await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText(/passed|future/i);await page.locator('#mc-when').fill('2030-10-08T23:00');await page.locator('[data-single]:not([data-when]) [data-value="text"]').click();await page.locator('[data-action="send"]').click();await expect(page.locator('#msg-fb')).toContainText(/8 AM.*9 PM/);});
  await check('failed save reports error and reenables action',async()=>{await fresh();await page.locator('#mc-body').fill('Unfinished draft');state.writeError='Fixture storage temporarily unavailable';await page.locator('[data-action="draft"]').click();await expect(page.locator('#msg-fb')).toContainText('temporarily unavailable');await expect(page.locator('[data-action="draft"]')).not.toHaveAttribute('aria-busy','true');state.writeError=null;});
  await check('failed test reports error',async()=>{await fresh();await page.locator('#mc-title').fill('Test');await page.locator('#mc-body').fill('Testing failure feedback');state.functionError='Fixture sending temporarily unavailable';await page.locator('[data-action="test-send"]').click();await expect(page.locator('#msg-fb')).toContainText('temporarily unavailable');state.functionError=null;});
  await check('keyboard focus visible on audience and fold',async()=>{await fresh();await page.keyboard.press('Tab');await group().focus();assert.equal(await group().evaluate(el=>getComputedStyle(el).outlineStyle),'solid');await page.locator('.msg-automatic > summary').focus();assert.equal(await page.locator('.msg-automatic > summary').evaluate(el=>getComputedStyle(el).outlineStyle),'solid');});
  await check('cancel schedule and delete draft update local list',async()=>{await fresh();await page.locator('[data-cancel="900002"]').click();await expect(page.locator('#msg-fb')).toContainText('Cancelled');assert.equal(state.messages.find(m=>m.id===900002).state,'draft');await page.locator('[data-del="900002"]').click();await expect(page.locator('[data-edit="900002"]')).toHaveCount(0);assert.equal(state.messages.some(m=>m.id===900002),false);});
  await check('self-test destinations identify current admin',async()=>{await fresh();await expect(page.locator('[data-test-target]')).toContainText('messages-admin@example.com');await page.locator('[data-single]:not([data-when]) [data-value="both"]').click();await expect(page.locator('[data-test-target]')).toContainText('(213) 555-0171');});
  await check('cohort selection survives draft reload',async()=>{await fresh();await group().click();await page.locator('.portal-or > summary').click();await page.locator('[data-cohorts] .portal-chip').first().click();await page.locator('#mc-body').fill('Cohort-specific draft');await page.locator('[data-action="draft"]').click();await expect(page.locator('#msg-fb')).toContainText('Saved as a draft');await expect(page.locator('[data-cohorts] .portal-chip[aria-pressed="true"]')).toHaveCount(1);assert.deepEqual(state.writes.at(-1).body.audience.cohort,['FA22']);});
  await check('overlapping save and test performs one write',async()=>{await fresh();await page.locator('#mc-title').fill('Concurrency test');await page.locator('#mc-body').fill('One write only');state.writeDelay=300;const beforeWrites=state.writes.length,beforeTests=state.calls.filter(c=>c.mode==='test').length;await page.locator('[data-action="draft"]').click();await expect(page.locator('[data-action="test-send"]')).toBeDisabled();await page.locator('[data-action="test-send"]').evaluate(el=>el.click());await expect(page.locator('#msg-fb')).toContainText('Saved as a draft');assert.equal(state.writes.length,beforeWrites+1);assert.equal(state.calls.filter(c=>c.mode==='test').length,beforeTests);state.writeDelay=0;});
  await check('shared contact receives one delivery across selected groups',async()=>{const original=state.people[1];state.people.push({...original,id:'00000000-0000-4000-8000-000000000005',full_name:'Shared Contact Member',divisions:['BUILD'],personal_email:`  ${original.personal_email.toUpperCase()}  `});try{await fresh();await group().click();await page.locator('[data-group="BUILD"][data-who="alumni"]').click();await page.locator('[data-single]:not([data-when]) [data-value="both"]').click();await page.locator('[data-action="preview"]').click();await expect(page.locator('[data-who-head]')).toContainText('2');await expect(page.locator('[data-who-items] .text-ink')).toHaveCount(2);await expect(page.locator('[data-who-items]')).toContainText(/shared|same|already.*included/i);await expect(page.locator('[data-aud-summary]')).toContainText(/email to 2.*text to 1/);}finally{state.people.pop();}});
  await check('roster load failure is visible and blocks sends',async()=>{state.failLoads=true;await page.goto(`${base}/alumni-portal/admin/messages`);await expect(page.locator('#msg-fb')).toContainText(/couldn.t|unable|try again|unavailable|failed/i,{timeout:20000});await expect(page.locator('[data-action="send"]')).toBeDisabled();state.failLoads=false;});
 }
 assert.deepEqual(state.errors,[],'no browser JS errors');await context.close();
} finally {await browser.close();}
assert.deepEqual(failures,[],'Messages UI regression failures');
console.log('PASS: all external requests mocked; no accounts created, messages sent or database writes made.');
