import { chromium, expect } from '@playwright/test';
import { adminClient, makeUser, signInPage } from './helpers.mjs';
import { mkdirSync, writeFileSync } from 'node:fs';
const admin=adminClient();let user,other,browser;const findings=[];const root=(process.env.PORTAL_URL || 'http://127.0.0.1:4321');
async function check(name,fn){try{await fn();findings.push({name,result:'PASS'});}catch(e){findings.push({name,result:'FAIL',error:e.message.slice(0,700)});}console.log(findings.at(-1));}
try{
 // counts are checked relative to the real members already in the database (the network is no longer empty)
 const count=async(q)=>(await q).count??0;
 const before={members:await count(admin.from('profiles').select('id',{count:'exact',head:true}).eq('approved',true)),alumni:await count(admin.from('profiles').select('id',{count:'exact',head:true}).eq('approved',true).eq('status','alum')),pending:await count(admin.from('profiles').select('id',{count:'exact',head:true}).eq('approved',false).is('declined_at',null))};
 user=await makeUser(admin,'Portal System QA');other=await makeUser(admin,'Portal Other QA',false);await admin.from('admins').insert({user_id:user.id});
 await admin.from('profiles').update({startups:['REMOVE ME'],divisions:['DESIGN','TECH'],city_id:null}).eq('id',user.id);
 browser=await chromium.launch();const {page}=await signInPage(browser,user);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`${root}/alumni-portal/profile`);await expect(page.locator('.portal-profile [data-action="save"]')).toBeEnabled();
 await check('Remove loaded profile tag',async()=>{await page.getByRole('button',{name:'Remove REMOVE ME',exact:true}).click();await expect(page.locator('#pf-startups')).not.toContainText('REMOVE ME',{timeout:1000});});
 await check('Personal contact save does not change auth identity',async()=>{const value=`contact-${user.id}@example.com`;await page.locator('#pf-personal').fill(value);await page.locator('[data-contact="personal"] button').click();await expect(page.locator('[data-contact="personal"] .portal-feedback')).toContainText('Saved');const {data}=await admin.auth.admin.getUserById(user.id);if(data.user.email!==user.session.user.email)throw Error('Auth identity unexpectedly changed');console.log('Confirmed separate contact and auth addresses');});
 await page.goto(`${root}/alumni-portal/home`);await expect(page.locator('.portal-explore-stats')).toBeVisible();
 await check('Member without city counted',async()=>{await expect(page.locator('.portal-explore-stats')).toContainText(`${before.members+1} PEOPLE`,{timeout:5000});});
 await check('Secondary division filter',async()=>{await page.locator('[data-filter="division"] button[data-value="TECH"]').click();await expect(page.locator('.portal-card-name')).toContainText('Portal System QA',{timeout:1000});});
 await page.goto(`${root}/alumni-portal/admin`);
 await check('Admin statistics',async()=>{await expect(page.locator('[data-stat="members"]')).toHaveText(String(before.members+1));await expect(page.locator('[data-stat-hint="members"]')).toContainText(`${before.alumni+1} alumni`);await expect(page.locator('[data-stat="pending"]')).toHaveText(String(before.pending+1));});
 await page.goto(`${root}/alumni-portal/admin/users`);await expect(page.locator(`[data-approve="${other.id}"]`)).toBeVisible();
 await check('Approve request',async()=>{await page.locator(`[data-approve="${other.id}"]`).click();await expect(page.locator(`[data-members] tr[data-id="${other.id}"]`)).toBeVisible();expect((await admin.from('profiles').select('approved').eq('id',other.id).single()).data.approved).toBe(true);});
 await check('Roles saved and reloaded',async()=>{await page.locator(`[data-roles-for="${other.id}"]`).click();await page.locator('[data-roles] button').filter({hasText:'DIRECTOR OF TECH'}).click();await page.locator('[data-roles] input[aria-label="Year"]').fill('2025');await page.locator('[data-action="save-roles"]').click();await expect(page.locator('[data-roles] .portal-feedback')).toContainText('Saved: 1');expect((await admin.from('eboard_roles').select('*').eq('profile_id',other.id)).data).toHaveLength(1);});
 await check('CSV export matches selected member',async()=>{await page.locator('#members-q').fill('Portal Other QA');const download=page.waitForEvent('download');await page.locator('[data-action="export"]').click();const d=await download;const stream=await d.createReadStream();let body='';for await(const chunk of stream)body+=chunk;expect(body).toContain('Portal Other QA');expect(body).not.toContain('Portal System QA');});
 await page.locator('a[href="/alumni-portal/admin/messages"]').click();await expect(page.locator('[data-aud-grid] button').first()).toBeVisible();
 await page.locator('a[href="/alumni-portal/admin/users"]').click();await expect(page.locator('[data-members]')).toBeVisible();
 await check('Member actions survive client navigation',async()=>{await expect(page.locator(`[data-roles-for="${other.id}"]`)).toBeVisible();await page.locator(`[data-roles-for="${other.id}"]`).click();await expect(page.locator('[data-roles]')).toBeVisible({timeout:1000});});
 await page.locator('a[href="/alumni-portal/admin/messages"]').click();await expect(page.locator('[data-aud-grid] button').first()).toBeVisible();
 await check('Save/edit draft without duplicates after navigation',async()=>{await page.locator('#mc-title').fill(`QA DRAFT ${user.id}`);await page.locator('#mc-body').fill('Disposable draft. Never send.');await page.locator('[data-aud-grid] .portal-chip[data-group="EVERYONE"][data-who="alumni"]').click();await page.locator('[data-action="draft"]').click();await expect(page.locator('[data-msg-list] li[data-state="draft"]')).toHaveCount(1,{timeout:3000});await page.locator('#mc-body').fill('Edited disposable draft. Never send.');await page.locator('[data-action="draft"]').click();await expect(page.locator('[data-msg-list] li[data-state="draft"]')).toHaveCount(1,{timeout:1500});});
 await check('Delete draft',async()=>{page.once('dialog',d=>d.accept());await page.locator('[data-del]').first().click();await expect(page.locator('[data-msg-list] li[data-state="draft"]')).toHaveCount(0,{timeout:1500});});
 await page.goto(`${root}/alumni-portal/admin/analytics`);await expect(page.locator('[data-stat="members"]')).toHaveText(String(before.members+2));await expect(page.locator('[data-site-source]')).not.toHaveText('from PostHog · counts only, nobody is tracked',{timeout:15000}).catch(()=>{}); console.log('Analytics source:',await page.locator('[data-site-source]').textContent());
 mkdirSync('test-results/system',{recursive:true});await page.screenshot({path:'test-results/system/admin.png',fullPage:true});
 console.log('page errors',errors);writeFileSync('test-results/system/findings.json',JSON.stringify(findings,null,2));if(findings.some(f=>f.result==='FAIL'))process.exitCode=1;
}finally{if(browser)await browser.close();if(user)await admin.from('messages').delete().eq('title',`QA DRAFT ${user.id}`);for(const u of [other,user])if(u)await u.cleanup();}
